In [1]:
import numpy as np

In [88]:
N = 5
delta = 0.05
dvc = 50

In [3]:
4*np.power(2*N, dvc)*np.exp(-N*np.power(0.05, 2)/8)

0.0

In [4]:
from scipy.optimize import fsolve

In [25]:
func = lambda N: 4*np.power(2*N, 10)*np.exp(-N*np.power(0.05, 2)/8)-0.05

In [26]:
fsolve(func, 450000)

array([452956.8647231])

In [45]:
import math
#e = sympy.Symbol('e')

In [66]:
vc_bound = lambda e: math.sqrt(8*math.log(4*math.pow(2*N, dvc)/0.05)/N)-e
#vc_bound = lambda e: np.sqrt(8*np.log(4*np.power(2*N, dvc)/0.05)/N)-e
#vc_bound = lambda e: 4*np.power(2*N, dvc)-delta*np.exp(N*np.power(e, 2)/8)
#sympy.solve(vc_bound, e)

In [68]:
rpb_bound = lambda e: math.sqrt(2*math.log(2*N*math.pow(N, dvc))/N)+math.sqrt(2*math.log(1/delta)/N)+(1/N)-e
#rpb_bound = lambda e: delta*math.exp(N*math.pow(np.sqrt(2*math.log(2*N*math.pow(N, dvc))/N)+(1/N)-e, 2)/2)-1

In [47]:
pvb_bound = lambda e: math.sqrt((2*e+math.log(6*math.pow(2*N, dvc)/delta))/N)-e

In [85]:
d_bound = lambda e: math.sqrt((4*e*(1+e)+math.log(4*math.pow(N, 2*dvc)/delta))/(2*N))-e

In [83]:
vvc_bound = lambda e: math.sqrt(16*math.log(2*math.pow(N, dvc)/math.sqrt(delta))/N)-e

In [89]:
fsolve(vc_bound, 0.5)

array([13.82816148])

In [90]:
fsolve(rpb_bound, 0.5)

array([7.04877656])

In [91]:
fsolve(pvb_bound, 0.5)

array([5.10136198])

In [92]:
fsolve(vvc_bound, 0.5)

array([16.26411106])

In [93]:
fsolve(d_bound, 0.5)

array([5.59312554])